### PR TITLE
Wschmidt

### PR DESCRIPTION
**Pull request by walkyd12**
Cleaning up files and file names and Robbie is giving me a run down of github pull requests.

### CODE REVIEW

**Comment by davemasino** [comment]
@walkyd12 did you mean to create a PR for merge into `fargate` ?

**Comment by Robbie-Smith** [comment]
@davemasino I just changed his base branch.

**Comment by walkyd12** [comment]
@davemasino yes I was, sorry about that. Robbie was giving me a run down of "best practices" so this was really just to walkthrough pull requests. Should be merging into fargate branch

**Comment by davemasino** [comment]
@walkyd12 all good! Thanks for sharing the knowledge @Robbie-Smith

**Pull request merged**
